const lieuData = {
    types: [
    "Alarme",
    "Alvéole bloquée",
    "Arbre HS",
    "Arrêt d'urgence",
    "Automatisme",
    "Autres",
    "Bande",
    "Bobine emmêlée/coincée",
    "Bourrage",
    "Bourrage de linge",
    "Bruleur",
    "Capteur",
    "Cintre cassé",
    "Cintre chute",
    "Cintres coincés",
    "Crochet cassé",
    "Décalage",
    "Decolleur",
    "Doigt / taquet cassé",
    "Double passe",
    "Electrique",
    "Film déchiré ou cassé",
    "Fuite air",
    "Fuite eau",
    "Galet tunnel HS",
    "Gaz",
    "Humaine",
    "Hydraulique",
    "Informatique",
    "Mauvais pliage / Pas de pliage",
    "Mauvais réglage",
    "Mécanique",
    "Membrane percée",
    "Moteur HS",
    "Navette cassée",
    "Pile",
    "Plomberie",
    "Plus de consommable",
    "Pneu déjanté",
    "Pneumatique",
    "Préventif Préventif",
    "Qualité",
    "Raccord/Tuyau cassé",
    "Rebut(s)",
    "Ressort cassé",
    "Roulement HS",
    "Sécurité",
    "Sling bloqué",
    "Sling mal ouvert/fermé",
    "Tapis",
    "Trolley bloqué",
    "Vapeur",
    "Z.Plus d'encre(Osbelete)",
    "Z.Plus d'étiquette(Osbelete)"
],



    causes: [
    "Arrêt d'urgence",
    "Automatisme",
    "Autre",
    "Bande cassée",
    "Bande(s) decalé(s)",
    "Bandes",
    "Bobine emmêlée/coincée",
    "Bourrage linge",
    "Capteur",
    "Capteur déréglé",
    "Chaine bloquée / cassée / détendue",
    "Cintre puce HS",
    "Cintres croisés",
    "Courbe métric usée",
    "Courroie usée / détendue",
    "Electrique",
    "Erreur de programmation",
    "Erreur humaine",
    "Fil coupé",
    "Frein déréglé ou cassé",
    "Fuite",
    "Manque de formation du personnel",
    "Pièce tordu",
    "Plus d'encre",
    "Plus d'étiquette",
    "Plus de bobine",
    "Plus de film",
    "Plus de produit",
    "Poussière / Salissure",
    "Rail usé",
    "Réglage",
    "Sling en travers",
    "Téflon usé",
    "Tuyau bouché",
    "Usures matériels",
    "Vis déssérée ou cassée",
    "Volume de linge trop important",
    "Z.Chaine cassée(Obselete)",
    "Z.Chaine(Obselete)",
    "Z.Cintre(Obselete)",
    "Z.Crochet cassé(Obselete)",
    "Z.Sécurité(Obselete)",
    "Z.Verin pneumatique(Osbelete"
] 
};

